name: example
description: A disposable provider example application.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  cupertino_icons: any
  disposable_provider:
    path: ..
  flutter:
    sdk: flutter
  rxdart: ">=0.26.0-0 <0.27.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true