name: disposable_provider
description: DisposableProvider is thin wrapper of Provider and it calls dispose automatically.
version: 2.2.0-dev
homepage: https://github.com/mono0926/disposable_provider
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.1.0-dev
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: